import { app, BrowserWindow } from 'electron';
import { createMainWindow } from './window';
import './handlers'; // Import IPC handlers

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

let mainWindow: BrowserWindow | null = null;

app.on('ready', () => {
  mainWindow = createMainWindow();
});

// Handle window close for macOS
app.on('window-all-closed', () => {
  // Don't quit on macOS when all windows are closed
  // Let the before-quit handler manage the quit process
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    mainWindow = createMainWindow();
  }
});
