import { BrowserWindow, app } from 'electron';
import * as path from 'path';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

let mainWindow: BrowserWindow | null = null;

export const createMainWindow = (): BrowserWindow => {
  // Get the icon path - works in both dev and production
  const iconPath = path.join(app.getAppPath(), 'build', 'icons', 'icon.png');

  mainWindow = new BrowserWindow({
    width: 1250,
    height: 800,
    minWidth: 1250,
    minHeight: 768,
    title: 'VibeMD',
    titleBarStyle: 'default',
    icon: iconPath,
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false, // Disable sandbox to allow preload script to work with webpack
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
    show: false, // Show after ready-to-show
  });

  // Set Content Security Policy to allow external images
  mainWindow.webContents.session.webRequest.onHeadersReceived((details, callback) => {
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        'Content-Security-Policy': ["default-src 'self' 'unsafe-inline' 'unsafe-eval' data: https:; img-src 'self' data: https:;"]
      }
    });
  });

  // Load renderer
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Show when ready
  mainWindow.once('ready-to-show', () => {
    mainWindow?.show();
  });

  // Handle closed
  mainWindow.on('closed', () => {
    mainWindow = null;
  });

  return mainWindow;
};

export const getMainWindow = (): BrowserWindow | null => mainWindow;

