name: Build Linux DEB

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build Linux DEB (x64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Linux x64
        run: npm run build:linux-x64

      - name: Upload DEB artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VibeMD-linux-x64-deb
          path: out/make/deb/x64/*.deb
          if-no-files-found: error
          retention-days: 30
