name: Build All Windows

on:
  workflow_dispatch:

jobs:
  build-x64:
    name: Windows x64
    uses: ./.github/workflows/build-windows-x64.yml

  build-arm64:
    name: Windows ARM64
    uses: ./.github/workflows/build-windows-arm64.yml
