name: Build All macOS and Linux

on:
  workflow_dispatch:

jobs:
  build-macos-silicon:
    name: macOS Silicon
    uses: vibemd/VibeMD/.github/workflows/build-macos-silicon.yml@main

  build-macos-intel:
    name: macOS Intel
    uses: vibemd/VibeMD/.github/workflows/build-macos-intel.yml@main

  build-linux-deb:
    name: Linux DEB
    uses: vibemd/VibeMD/.github/workflows/build-linux-deb.yml@main

  build-linux-rpm:
    name: Linux RPM
    uses: vibemd/VibeMD/.github/workflows/build-linux-rpm.yml@main
