name: Build Linux Packages

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'site/**'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x64
            command: build:linux-x64
    env:
      npm_config_arch: ${{ matrix.arch }}
      ELECTRON_CACHE: ${{ runner.temp }}/electron
      ELECTRON_BUILDER_CACHE: ${{ runner.temp }}/electron-builder
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Homebrew packaging tools
        run: brew install dpkg fakeroot rpm

      - name: Install dependencies
        run: npm ci

      - name: Determine version
        id: meta
        shell: bash
        run: echo "version=$(node -p \"require('./package.json').version\")" >> "$GITHUB_OUTPUT"

      - name: Ensure version is unreleased
        shell: bash
        env:
          VERSION: ${{ steps.meta.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if gh release view "v${VERSION}" >/dev/null 2>&1; then
            echo "Release v${VERSION} already exists. Please increment the project version before building." >&2
            exit 1
          fi

      - name: Run smoke tests
        run: node scripts/run-smoke-tests.js

      - name: Build artifacts
        run: npm run ${{ matrix.command }}

      - name: Validate staged release assets
        id: staged
        shell: bash
        run: |
          set -euo pipefail
          release_dir="releases/linux/${{ matrix.arch }}"
          if [ ! -d "$release_dir" ]; then
            echo "Release directory missing: $release_dir" >&2
            exit 1
          fi
          mapfile -t files < <(find "$release_dir" -maxdepth 1 -type f \( -name "*.deb" -o -name "*.rpm" \))
          if [ "${#files[@]}" -eq 0 ]; then
            echo "No DEB or RPM artifacts staged under $release_dir" >&2
            exit 1
          fi
          filelist_path="$release_dir/.filelist.txt"
          printf '%s\n' "${files[@]}" > "$filelist_path"
          echo "dir=$release_dir" >> "$GITHUB_OUTPUT"
          echo "filelist=$filelist_path" >> "$GITHUB_OUTPUT"

      - name: Create manifest
        shell: bash
        env:
          ARTIFACT_VERSION: ${{ steps.meta.outputs.version }}
          ARTIFACT_PLATFORM: linux
          ARTIFACT_ARCH: ${{ matrix.arch }}
          ARTIFACT_FILELIST_PATH: ${{ steps.staged.outputs.filelist }}
          ARTIFACT_MANIFEST_PATH: ${{ steps.staged.outputs.dir }}/manifest.json
        run: |
          node scripts/create-artifact-manifest.js
          rm -f "${{ steps.staged.outputs.filelist }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-linux-${{ matrix.arch }}-v${{ steps.meta.outputs.version }}
          path: ${{ steps.staged.outputs.dir }}
          if-no-files-found: error
          retention-days: 21
