name: Build Windows x64

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build Windows x64
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Windows x64
        run: npm run build:win-x64

      - name: Upload ZIP artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VibeMD-win32-x64-zip
          path: out/make/zip/win32/x64/*.zip
          if-no-files-found: error
          retention-days: 30

      - name: Upload WiX MSI artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VibeMD-win32-x64-msi
          path: out/make/wix/x64/*.msi
          if-no-files-found: error
          retention-days: 30
