name: Build Windows x64

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      version:
        description: 'Version to build'
        required: false
        type: string

jobs:
  build:
    name: Build Windows x64
    runs-on: windows-latest
    env:
      WINDOWS_CERT_BASE64: ${{ secrets.WINDOWS_CERT_BASE64 }}
      WINDOWS_CERT_PASSWORD: ${{ secrets.WINDOWS_CERT_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Setup Windows signing cert
        if: env.WINDOWS_CERT_BASE64 != ''
        shell: pwsh
        run: |
          $pfxPath = "$env:RUNNER_TEMP\codesign.pfx"
          [IO.File]::WriteAllBytes($pfxPath, [Convert]::FromBase64String($env:WINDOWS_CERT_BASE64))
          "WINDOWS_CERT_PATH=$pfxPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Verify version consistency
        shell: pwsh
        run: |
          $pkg = (Get-Content package.json -Raw | ConvertFrom-Json).version
          Write-Host "package.json version: $pkg"
          if ('${{ inputs.version }}' -and $pkg -ne '${{ inputs.version }}') {
            Write-Error "Version mismatch! package.json has $pkg but workflow expects ${{ inputs.version }}"
            exit 1
          }
          Write-Host "Version verification passed"

      - name: Build Windows x64
        run: npm run build:win-x64

      - name: Upload Squirrel EXE artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VibeMD-win32-x64-exe
          path: out/make/squirrel.windows/x64/*.exe
          if-no-files-found: error
          retention-days: 30

      - name: Upload ZIP artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VibeMD-win32-x64-zip
          path: out/make/zip/win32/x64/*.zip
          if-no-files-found: error
          retention-days: 30

      - name: Upload WiX MSI artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VibeMD-win32-x64-msi
          path: out/make/wix/x64/*.msi
          if-no-files-found: error
          retention-days: 30
